site_name: Entwicklung und Betrieb mobiler Informationssysteme
site_description: Entwicklung und Betrieb mobiler Informationssysteme
site_author: Stefan Huber

repo_url: https://github.com/stefanhuber/ebmi
edit_uri: https://github.com/stefanhuber/ebmi

nav:
  - Home: 'index.md'
  #- 'Android':
  #  - 'u1': 'android\sixteen-buttons.md'
  #  - 'u2': 'android\snake.md'
  - 'Mobile Web':
    - 'Draggable Grid': 'mobile-web/draggable-grid.md'
    - 'Fx Calculator': 'mobile-web/fx-calculator.md'

theme:
  name: material
  language: de
  features:
    - tabs
  icon:
    logo: fontawesome/solid/mobile-alt

copyright: 'CC-BY-SA / Stefan Huber'

docs_dir: content
site_dir: docs

extra:
  search:
    language: de

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search:
      lang: de
  
